// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMINWgupdAzhdW60Q8PFGVe3T82CGtFwY',
    appId: '1:871350869965:web:430de0710920abd7a66e84',
    messagingSenderId: '871350869965',
    projectId: 'tropical-64d1b',
    authDomain: 'tropical-64d1b.firebaseapp.com',
    databaseURL: 'https://tropical-64d1b-default-rtdb.firebaseio.com',
    storageBucket: 'tropical-64d1b.firebasestorage.app',
    measurementId: 'G-7LGV1JL99L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1OWLtzzEYx3z9MStOMxHmM3YCgRw_N0',
    appId: '1:871350869965:android:422d724e338b8c88a66e84',
    messagingSenderId: '871350869965',
    projectId: 'tropical-64d1b',
    databaseURL: 'https://tropical-64d1b-default-rtdb.firebaseio.com',
    storageBucket: 'tropical-64d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLeQrizv-doMJENJiTh2fq3WgWtAaczg',
    appId: '1:871350869965:ios:dc8f4a95624336bfa66e84',
    messagingSenderId: '871350869965',
    projectId: 'tropical-64d1b',
    databaseURL: 'https://tropical-64d1b-default-rtdb.firebaseio.com',
    storageBucket: 'tropical-64d1b.firebasestorage.app',
    iosBundleId: 'com.tropical.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLeQrizv-doMJENJiTh2fq3WgWtAaczg',
    appId: '1:871350869965:ios:dc8f4a95624336bfa66e84',
    messagingSenderId: '871350869965',
    projectId: 'tropical-64d1b',
    databaseURL: 'https://tropical-64d1b-default-rtdb.firebaseio.com',
    storageBucket: 'tropical-64d1b.firebasestorage.app',
    iosBundleId: 'com.tropical.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMINWgupdAzhdW60Q8PFGVe3T82CGtFwY',
    appId: '1:871350869965:web:fe6d6ea5b9681c27a66e84',
    messagingSenderId: '871350869965',
    projectId: 'tropical-64d1b',
    authDomain: 'tropical-64d1b.firebaseapp.com',
    databaseURL: 'https://tropical-64d1b-default-rtdb.firebaseio.com',
    storageBucket: 'tropical-64d1b.firebasestorage.app',
    measurementId: 'G-5JNF48WCTG',
  );
}

